### PR TITLE
Add podspec for react-native autolinking

### PR DESCRIPTION
**Pull request by karlvr**
https://github.com/react-native-community/cli/blob/master/docs/autolinking.md

### CODE REVIEW

**Comment by karlvr** [comment]
Whoops, I just saw #6. I made the move of setting the pod name to `RNScreenshotDetector` so that the import statements in `AppDelegate.m` didn't need to be changed. Is that a useful addition to your much more comprehensive PR @iamacup?

**Comment by iamacup** [comment]
Ahhh is that how its done - great - i will add it 👍

**Comment by jeremybenaim** [comment]
@iamacup hey there, any plan to merge this PR and bump it to npm? Thanks 🙏

**Comment by jeremybenaim** [comment]
@blend hey there, any plan to merge this PR and bump it to npm? Thanks 🙏

**Comment by m-tymchyk** [comment]
@blend please merge this PR 🙏

**Comment by iamacup** [comment]
I have published my pull request on npm as `react-native-screenshot-detect` for easy access to this because its been annoying me for awhile now... :)

**Comment by karlvr** [comment]
Refer to #6

**Pull request closed without merging**
